version: "3"
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: plooral
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    # restart: unless-stopped
