org: mapdev
service: trigger-jobs

frameworkVersion: "3"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x
  region: ${file(./values.yml):${self:provider.stage}.REGIAO}
  stage: ${opt:stage,'develop'}
  tracing:
    lambda: true
  vpc:
    securityGroupIds:
      - ${file(./values.yml):${self:provider.stage}.SECURITY_GROUP_API}
    subnetIds:
      - ${file(./values.yml):${self:provider.stage}.SUBNET1}
      - ${file(./values.yml):${self:provider.stage}.SUBNET2}
  environment:
    TZ: ${file(./values.yml):${self:provider.stage}.TZ}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
          Resource:
            - { "Fn::GetAtt": ["EventsQueue", "Arn"] }

package:
  individually: false

custom:
  package: ${file(package.json)}
  webpack:
    webpackConfig: "webpack.config.js"
    excludeFiles:
      - "**/*.spec.ts"
      - "**/*.ispec.ts"
  # bundle:
  #   externals:
  #     - axios

functions:
  handlerNotificationEvents:
    name: trigger-events-${self:provider.stage}
    handler: src/index._eventListenner
    memorySize: 1024
    timeout: 60 #tempo em segundos
    # integration: lambda
    events:
      - sqs:
          arn:
            Fn::GetAtt: ["EventsQueue", "Arn"]
          batchSize: 10
          # functionResponseType: ReportBatchItemFailures

resources:
  Resources:
    EventsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.package.name}-${self:provider.stage}-trigger-events-queue
        VisibilityTimeout: 900
        MessageRetentionPeriod: 86400
        ReceiveMessageWaitTimeSeconds: 20
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - EventsQueueDLQ
              - Arn
          maxReceiveCount: 3
    EventsQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.package.name}-${self:provider.stage}-trigger-events-queue-dlq
        VisibilityTimeout: 900
        MessageRetentionPeriod: 86400
        ReceiveMessageWaitTimeSeconds: 20

    # SQS-SNS Publicar um job
    SNSSubscriptionPublishJobEvent:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: { "Fn::GetAtt": ["EventsQueue", "Arn"] }
        TopicArn:
          Fn::Join:
            - ":"
            - - "arn:aws:sns"
              - Ref: "AWS::Region"
              - Ref: "AWS::AccountId"
              - "event_publish_job"

    # Allow SNS to send messages to SQS
    EventsQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - { Ref: EventsQueue }
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: allow-sns-messages
              Effect: Allow
              Principal:
                Service: sns.amazonaws.com
              Action: sqs:SendMessage
              Resource:
                Fn::GetAtt:
                  - EventsQueue
                  - Arn
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Fn::Join:
                      - ":"
                      - - arn
                        - aws
                        - sns
                        - Ref: AWS::Region
                        - Ref: AWS::AccountId
                        - event_*
